functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность переключить язык интерфейса
  - Пользователь может пользоваться постраничным выводом
  - Пользователь может удалять товары из корзины
  - Пользователь может на странице корзины продолжить выбирать товары
  - Пользователь может на странице корзины оформить заказ и перейти на страницу оплаты
non-functional:
  - Сайт нужно оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию (быть адаптивным)
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Сайт может обрабатывать большое количество трафика (масштабируемость)
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен иметь локализацию (перевод) на русский и английский языки
  - Сайт должен быть SPA-приложением (без перезагрузки страниц).
implicit:
  - При обновлении страницы корзина должна сохранять содержимое в рамках текущей сессии браузера
  - Сайт должен корректно отображать ошибки (например, при оплате или загрузке товаров)
  - Корзина должна сохраняться при обновлении страницы в рамках сессии браузера
  - Пользователь должен получать подтверждение о добавлении товара в корзину
  - При оформлении заказа должна быть проверка введённых данных (валидность e-mail, телефона)
  - Должна быть реализована страница 404 и обработка ошибок навигации
  - Язык интерфейса должен переключаться без перезагрузки страницы (так как это SPA-приложение)
  - Цены и скидки должны быть единообразными и отображаться корректно на всех страницах (каталог, карточка товара, корзина, оформление заказа)
